# Use an official lightweight Node.js image
FROM node:alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 5000 for the application
EXPOSE 5000

# Run the node app
CMD ["node", "index.js"]
